controller_joint_names: ['', 'joint1_lrf', 'joint1.1_lrf', 'joint1.2_lrf', 'joint1_lrb', 'joint1.1_lrb', 'joint1.2_lrb', 'joint1_llf', 'joint1.1_llf', 'joint1.2_llf', 'joint1_llb', 'joint1.1_llb', 'joint1.2_llb', ]
