controller_joint_names: ['', 'wl1.joint1', 'wl1.joint2', 'wl1.joint3', 'wl2.joint1', 'wl2.joint2', 'wl2.joint3', 'wl3.joint1', 'wl3.joint2', 'wl3.joint3', 'wl4.joint1', 'wl4.joint2', 'wl4.joint3', ]
